project:
  type: book
  output-dir: docs
  

book:
  title: "Parallel Computing Assignment"
  author: "Aphinda Jabe"
  date: "2026/03/04"
  chapters:
    - index.qmd
    - Parallel Computing.qmd


format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

